/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dt_model_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = {8, 8, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 4, 5};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s5[9] = {8, 2, 0, 2, 4, 4, 6, 5, 7};
static const casadi_int casadi_s6[5] = {0, 2, 0, 0, 0};

/* dt_model_constr_h_fun_jac_uxt_zt_hess:(i0[4],i1[4],i2[2],i3[],i4[13])->(o0[2],o1[8x2,4nz],o2[8x8,4nz],o3[0x2],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, *w6=w+9, *w7=w+15, *w8=w+17, *w9=w+19, *w10=w+23, *w11=w+31;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #6: @4 = @0[3] */
  for (rr=(&w4), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #7: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #8: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #9: @0 = zeros(8x2,4nz) */
  casadi_clear(w0, 4);
  /* #10: @6 = ones(8x1,6nz) */
  casadi_fill(w6, 6, 1.);
  /* #11: {NULL, @7} = vertsplit(@6) */
  casadi_copy(w6+4, 2, w7);
  /* #12: @5 = @7[0] */
  for (rr=(&w5), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #13: @2 = (@2*@5) */
  w2 *= w5;
  /* #14: @5 = @7[1] */
  for (rr=(&w5), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #15: @4 = (@4*@5) */
  w4 *= w5;
  /* #16: @7 = vertcat(@2, @4) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w4;
  /* #17: (@0[:4:2] = @7) */
  for (rr=w0+0, ss=w7; rr!=w0+4; rr+=2) *rr = *ss++;
  /* #18: @7 = ones(8x1,2nz) */
  casadi_fill(w7, 2, 1.);
  /* #19: {NULL, @8} = vertsplit(@7) */
  casadi_copy(w7, 2, w8);
  /* #20: @2 = @8[0] */
  for (rr=(&w2), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #21: @1 = (@1*@2) */
  w1 *= w2;
  /* #22: @2 = @8[1] */
  for (rr=(&w2), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #23: @3 = (@3*@2) */
  w3 *= w2;
  /* #24: @8 = vertcat(@1, @3) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w3;
  /* #25: (@0[1:5:2] = @8) */
  for (rr=w0+1, ss=w8; rr!=w0+5; rr+=2) *rr = *ss++;
  /* #26: output[1][0] = @0 */
  casadi_copy(w0, 4, res[1]);
  /* #27: @0 = zeros(8x8,4nz) */
  casadi_clear(w0, 4);
  /* #28: @9 = zeros(4x1) */
  casadi_clear(w9, 4);
  /* #29: @8 = input[2][0] */
  casadi_copy(arg[2], 2, w8);
  /* #30: {@1, @3} = vertsplit(@8) */
  w1 = w8[0];
  w3 = w8[1];
  /* #31: @10 = ones(8x1) */
  casadi_fill(w10, 8, 1.);
  /* #32: {NULL, @11} = vertsplit(@10) */
  casadi_copy(w10+4, 4, w11);
  /* #33: @2 = @11[1] */
  for (rr=(&w2), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #34: @2 = (@3*@2) */
  w2  = (w3*w2);
  /* #35: (@9[3] += @2) */
  for (rr=w9+3, ss=(&w2); rr!=w9+4; rr+=1) *rr += *ss++;
  /* #36: @2 = @11[3] */
  for (rr=(&w2), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #37: @3 = (@3*@2) */
  w3 *= w2;
  /* #38: (@9[1] += @3) */
  for (rr=w9+1, ss=(&w3); rr!=w9+2; rr+=1) *rr += *ss++;
  /* #39: @3 = @11[0] */
  for (rr=(&w3), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #40: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #41: (@9[2] += @3) */
  for (rr=w9+2, ss=(&w3); rr!=w9+3; rr+=1) *rr += *ss++;
  /* #42: @3 = @11[2] */
  for (rr=(&w3), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #43: @1 = (@1*@3) */
  w1 *= w3;
  /* #44: (@9[0] += @1) */
  for (rr=w9+0, ss=(&w1); rr!=w9+1; rr+=1) *rr += *ss++;
  /* #45: (@0[:4] = @9) */
  for (rr=w0+0, ss=w9; rr!=w0+4; rr+=1) *rr = *ss++;
  /* #46: @9 = @0' */
  casadi_trans(w0,casadi_s0, w9, casadi_s0, iw);
  /* #47: output[2][0] = @9 */
  casadi_copy(w9, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int dt_model_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dt_model_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dt_model_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dt_model_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dt_model_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dt_model_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dt_model_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void dt_model_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dt_model_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int dt_model_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real dt_model_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dt_model_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dt_model_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dt_model_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dt_model_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s5;
    case 2: return casadi_s0;
    case 3: return casadi_s6;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dt_model_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 35;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
